spring.application.name=scraper-service
api.key=dev-api-key

# Logging
logging.level.com.chan.scraper=DEBUG
logging.level.org.jsoup=DEBUG

#db
spring.datasource.url=jdbc:postgresql://localhost:5432/scraper_db
spring.datasource.username=scraper_user
spring.datasource.password=scraper_pass
spring.datasource.driver-class-name=org.postgresql.Driver

#JPA/ Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.jpa.properties.hibernate.jdbc.time_zone=UTC

#Logging
logging.level.com.chan.scraper_service=DEBUG

#schedluer
scraper.schedule.cron=0 59 23 * * *
