spring.application.name=scraper-service
# JPA - no DB needed yet, disable auto-config temporarily
spring.autoconfigure.exclude=\
  org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,\
  org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

# Logging
logging.level.com.chan.scraper=DEBUG
logging.level.org.jsoup=DEBUG
