apiVersion: apps/v1
kind: Deployment
metadata:
  name: scraper-app
  labels:
    app: scraper-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scraper-app
  template:
    metadata:
      labels:
        app: scraper-app
    spec:
      containers:
        - name: scraper-app
          image: scraper-app:0.1
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: scraper-config
            - secretRef:
                name: scraper-secret
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
